Feature/hw 1 hangman
dmytrochornyy/Practice pull request #6
Opened 2020-11-11 12:01 UTC by dmytrochornyy

Asking to check my history one more time

2020-11-13 22:03 UTC, Hozhyi requested changes
That was only overall look

2020-11-13 22:03 UTC, Hozhyi commented on hangman/hangman.py
> +def hangman_with_hints(secret_word):
The code of this function and function hangman are duplicating each other in many terms. Try to make 1 function which can be used in both ways

2020-11-13 22:03 UTC, Hozhyi commented on hangman/hangman.py
> +    #show_possible_matches("t_ _ t")
Commented code - is a dead one, there's no sense to have it, just remove

2020-11-20 10:57 UTC, dmytrochornyy commented
Hi! I`ve fully rebuild my game! Could you look at it one more time, please? @Hozhyi

2020-11-23 15:19 UTC, Hozhyi requested changes

2020-11-23 15:19 UTC, Hozhyi commented on hangman/hangman.py
> +    my_word = my_word.replace(" ", "")
You could delete them on 1 level up, as you call this function many time with the same `my_word`

2020-11-23 15:19 UTC, Hozhyi commented on hangman/hangman.py
> +    else:
I think you don't need this `else` statement here, as `return` in scope of previous `if` will return from this function

2020-11-23 15:19 UTC, Hozhyi commented on hangman/hangman.py
> +        if my_word[i] != "_" and my_word[i] != other_word[i]:
Have you taken into account that result for the following two words should be `False`:
a_bc
abbc

2020-11-23 15:19 UTC, Hozhyi commented on hangman/hangman.py
> +        guesses_remaining, warnings_remaining, letter_is_correct, msg = letter_checker(letter, letters_guessed, guesses_remaining, warnings_remaining)
This is quite long line, try to split it into 2 lines of code

2020-11-23 15:19 UTC, Hozhyi commented on hangman/hangman.py
> +        if hints_on and letter == "*":
It seems like you reduce number of warnings when user ask for hints, isn't it?

2020-11-23 15:19 UTC, Hozhyi commented on hangman/hangman.py
> +      sep=""
What is the default value of `sep`?

2020-11-23 15:19 UTC, Hozhyi commented on hangman/hangman.py
> +      if not letters_guessed[letter]:
Ah.. I see - you use dictionary (although in the function docstring mentioned that `letters_guessed` is a list object)

2020-11-23 15:19 UTC, Hozhyi commented on hangman/hangman.py
> +    letters_guessed = {i: 0 for i in string.ascii_lowercase}
It would be more logical for me to use a `set` here, which will represent set of entered letters

2020-11-30 13:25 UTC, dmytrochornyy commented on hangman/hangman.py
> +# Collaborators: Made by myself (Can help others with some ideas)
Done

2020-11-30 13:25 UTC, dmytrochornyy commented on hangman/hangman.py
> +      #if at least one letter is not guessed
Solved

2020-11-30 13:25 UTC, dmytrochornyy commented on hangman/hangman.py
> +      if not letters_guessed[letter]:
Solved

2020-11-30 13:25 UTC, dmytrochornyy commented on hangman/hangman.py
> +        guessed_word +="_ "
Solved

2020-11-30 13:25 UTC, dmytrochornyy commented on hangman/hangman.py
> +    for letter in letters_guessed.keys():
Solved

2020-11-30 13:25 UTC, dmytrochornyy commented on hangman/hangman.py
> +        available_letters += letter
Solved

2020-11-30 13:26 UTC, dmytrochornyy commented on hangman/hangman.py
> +    )
Solved

2020-11-30 13:26 UTC, dmytrochornyy commented on hangman/hangman.py
> +  elif letter in "aeiou":
Changed to tuple

2020-11-30 13:26 UTC, dmytrochornyy commented on hangman/hangman.py
> +  return guesses_remaining*len(set(secret_word))
Solved

2020-11-30 13:26 UTC, dmytrochornyy commented on hangman/hangman.py
> +    else:
You`re right

2020-11-30 13:27 UTC, dmytrochornyy commented on hangman/hangman.py
> +        if my_word[i] != "_" and my_word[i] != other_word[i]:
Thank you! Solved.

2020-11-30 13:27 UTC, dmytrochornyy commented on hangman/hangman.py
> +        guesses_remaining, warnings_remaining, letter_is_correct, msg = letter_checker(letter, letters_guessed, guesses_remaining, warnings_remaining)
Done with temp_tuple

2020-11-30 13:27 UTC, dmytrochornyy commented on hangman/hangman.py
> +        if hints_on and letter == "*":
True. Solved.

2020-11-30 13:32 UTC, dmytrochornyy commented on hangman/hangman.py
> +      sep=""
Done

2020-11-30 13:40 UTC, dmytrochornyy commented on hangman/hangman.py
> +    "I am thinking of a word that is {0} letters long.".format(len(secret_word)),
Thank you! Forgot about them.

2020-11-30 14:31 UTC, dmytrochornyy commented on hangman/hangman.py
> +    letters_guessed = {i: 0 for i in string.ascii_lowercase}
as for me, it easier to work with dictionary, for example, it`s enough to write letters_guessed[letter], to check if letter was already guessed. Moreover, as far a know, it faster, to find letter value in dict (letters_guessed[letter]), than find it in tuple (letter in letters_guessed). Im attaching my proof, can you please tell me if i checked speed correctly?

Could not attach file here, I will send it to you in Slack!

2020-11-30 14:48 UTC, dmytrochornyy commented on hangman/hangman.py
> +    my_word = my_word.replace(" ", "")
True. Thank you!

2020-11-30 15:14 UTC, dmytrochornyy commented
Hi! I`ve done all changes due to your comments. Could you check this one more time please? @Hozhyi

2020-12-01 12:06 UTC, dmytrochornyy commented
Hi! I did all changes that you said. Could you please check that one more time? @Hozhyi

2020-12-04 14:12 UTC, Hozhyi requested changes

2020-12-04 14:12 UTC, Hozhyi commented on hangman/hangman.py
> +            available_letters = available_letters.replace(letter, '')
Replace function need to look at each letter to check whether this letter needs to be removed. Effectively - it's will be O(n^2). You can make it faster.

2020-12-04 14:12 UTC, Hozhyi commented on hangman/hangman.py
> +    warnings_remaining: int, remaining warnings
Can't see here a description about `hints_on` parameter

2020-12-04 14:12 UTC, Hozhyi commented on hangman/hangman.py
> +    if letter=="*" and hints_on:
Could you wrap sign "==" with spaces around?

2020-12-04 14:12 UTC, Hozhyi commented on hangman/hangman.py
> +    vovels = (i for i in "aeiou")
I'd create a separate constant for that variable, and tried to find a better container type

2020-12-04 14:12 UTC, Hozhyi commented on hangman/hangman.py
> +        guesses_remaining, warnings_remaining, letter_is_correct, msg = temp_tuple
I'd tried to shorten it a bit differ:
```
guesses_remaining, warnings_remaining, letter_is_correct, msg =
    letter_checker(letter, letters_guessed, guesses_remaining, warnings_remaining, hints_on)
```

2020-12-04 14:12 UTC, Hozhyi commented on hangman/hangman.py
> +        temp_tuple = letter_checker(letter, letters_guessed, guesses_remaining, warnings_remaining, hints_on)
You could check whether user asks hints first and `continue` if he does, then you won't need check it inside `letter_checker` function and won't need additional parameter `hints_on`

2020-12-04 14:12 UTC, Hozhyi commented on hangman/hangman.py
> +
Have you read PEP recommendations?

2020-12-05 12:51 UTC, dmytrochornyy commented
Hi, @Hozhyi ! Did all you said, could you check one more time please?)

2020-12-09 23:02 UTC, Hozhyi requested changes

2020-12-09 23:02 UTC, Hozhyi commented on hangman/hangman.py
> +        elif (my_word[i] == "_") and (other_word[i] in my_word):
You use that "_" symbol so often, that it also makes sense to create a constant for it

2020-12-09 23:02 UTC, Hozhyi commented on hangman/hangman.py
> +    print(*list_with_mathes)
According to task description - here should be different output

2020-12-09 23:02 UTC, Hozhyi commented on hangman/hangman.py
> +    #create blank letters 0/1-table. 0(False) - if letter is not guessed - 1(True) otherwise
Seems that this comment is outdated

2020-12-13 10:37 UTC, Hozhyi requested changes

2020-12-13 10:37 UTC, Hozhyi commented on hangman/hangman.py
> +        print("\nCongratulations, you won!",
Could you add a separate empty print, apart from adding `\n` special symbols, it's will be more readable

2020-12-13 10:37 UTC, Hozhyi commented on hangman/hangman.py
> +            print("Possible word matches are: ", end="")
Could you include that print into `show_possible_matches`?

2020-12-13 10:37 UTC, Hozhyi commented on hangman/hangman.py
> +        if letter == "*" and hints_on:
I believe it makes sense to make this "*" symbol as constant as well

2020-12-16 00:23 UTC, Hozhyi approved these changes

2020-12-16 10:24 UTC, merged